# Base configuration (not a service, just a reusable config block)
x-base-config: &base-config
  ports:
    - "11235:11235"
    - "8001:8000"
    - "9223:9222"
    - "8081:8080"
  environment:
    - CRAWL4AI_API_TOKEN=${CRAWL4AI_API_TOKEN:-}
    - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    - CLAUDE_API_KEY=${CLAUDE_API_KEY:-}
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - LOG_LEVEL=DEBUG  # 로깅 레벨 추가
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"
      tag: "{{.Name}}"
  volumes:
    - /dev/shm:/dev/shm
    - ./logs:/app/logs  # 로그 볼륨 마운트 추가
    - ./.profiles:/app/.profiles  # 프로필 마운트 추가
  deploy:
    resources:
      limits:
        memory: 4G
      reservations:
        memory: 1G
  restart: unless-stopped
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:11235/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s
  depends_on:
    - redis

services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Local build services for different platforms
  crawl4ai-amd64:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.10"
        INSTALL_TYPE: ${INSTALL_TYPE:-basic}
        ENABLE_GPU: false
      platforms:
        - linux/amd64
    profiles: ["local-amd64"]
    <<: *base-config

  crawl4ai-arm64:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.10"
        INSTALL_TYPE: ${INSTALL_TYPE:-basic}
        ENABLE_GPU: false
      platforms:
        - linux/arm64
    profiles: ["local-arm64"]
    <<: *base-config

  # Hub services for different platforms and versions
  crawl4ai-hub-amd64:
    image: unclecode/crawl4ai:${VERSION:-basic}-amd64
    profiles: ["hub-amd64"]
    <<: *base-config

  crawl4ai-hub-arm64:
    image: unclecode/crawl4ai:${VERSION:-basic}-arm64
    profiles: ["hub-arm64"]
    <<: *base-config

volumes:
  redis_data:
    driver: local